language: ruby
rvm:
  - 2.4.1
env:
  - RACK_ENV=test
before_script:
  - cp config/database.travis.yml config/database.yml
    #  - bundle exec rake db:create db:schema:load
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
