language: ruby
rvm:
  - "2.4.1"
script:
  #- RACK_ENV=test bundle exec rake --trace db:create db:migrate
  - RACK_ENV=test bundle exec rake --trace db:schema:load
  - RACK_ENV=test bundle exec rake --trace db:test:prepare
  - RACK_ENV=test bundle exec rspec spec/
